server:
  port: 5000
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8764/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
     userapi:
        path: /userapi/**
        serviceId: adidas-user

